#!/usr/bin/env python3
"""Generate process catalog CSV files for Liquibase fake-data."""

from pathlib import Path

BASE = Path(__file__).resolve().parents[1] / "src/main/resources/config/liquibase/fake-data/catalog"


def write_csv(path: Path, header: str, rows: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(header + "\n" + "\n".join(rows) + "\n", encoding="utf-8")


def write_rel_named(path: Path, col2: str, pairs: list[tuple[int, int]]) -> None:
    rows = [f"{a};{b}" for a, b in pairs]
    write_csv(path, f"activity_id;{col2}", rows)


def write_process_data(
    folder: str,
    phases: list[tuple[int, str, str, int]],
    activities: list[dict],
) -> None:
    proc_dir = BASE / "processes" / folder

    write_csv(
        proc_dir / "phase.csv",
        "id;name;description;process_id",
        [f"{i};{n};{d};{p}" for i, n, d, p in phases],
    )

    act_rows = [f"{a['id']};{a['name']};{a['desc']};{a['input']};{a['phase']}" for a in activities]
    write_csv(proc_dir / "activity.csv", "id;name;description;input_criterion;phase_id", act_rows)

    resp: list[tuple[int, int]] = []
    part: list[tuple[int, int]] = []
    req: list[tuple[int, int]] = []
    prod: list[tuple[int, int]] = []
    subs: list[tuple[int, int]] = []
    tools: list[tuple[int, int]] = []
    guides: list[tuple[int, int]] = []
    tmpls: list[tuple[int, int]] = []

    for a in activities:
        aid = a["id"]
        for r in a.get("responsible", []):
            resp.append((aid, r))
        for r in a.get("participants", []):
            part.append((aid, r))
        for r in a.get("required", []):
            req.append((aid, r))
        for r in a.get("produced", []):
            prod.append((aid, r))
        for r in a.get("deps", []):
            subs.append((r, aid))
        for t in a.get("tools", []):
            tools.append((aid, t))
        for g in a.get("guidelines", []):
            guides.append((aid, g))
        for t in a.get("templates", []):
            tmpls.append((aid, t))

    write_rel_named(proc_dir / "rel_activity__responsible_roles.csv", "responsible_roles_id", resp)
    write_rel_named(proc_dir / "rel_activity__participant_roles.csv", "participant_roles_id", part)
    write_rel_named(proc_dir / "rel_activity__required_artifacts.csv", "required_artifacts_id", req)
    write_rel_named(proc_dir / "rel_activity__produced_artifacts.csv", "produced_artifacts_id", prod)
    write_rel_named(proc_dir / "rel_activity__sub_activities.csv", "sub_activities_id", subs)
    write_rel_named(proc_dir / "rel_activity__tools.csv", "tools_id", tools)
    write_rel_named(proc_dir / "rel_activity__guidelines.csv", "guidelines_id", guides)
    write_rel_named(proc_dir / "rel_activity__templates.csv", "templates_id", tmpls)


def generate_library() -> None:
    lib = BASE / "library"

    roles = [
        (1, "Product Owner", "Prioriza backlog e define valor de negócio do produto"),
        (2, "Scrum Master", "Facilita cerimônias ágeis e remove impedimentos"),
        (3, "Desenvolvedor Backend", "Implementa APIs, regras de negócio e integrações"),
        (4, "Desenvolvedor Frontend", "Desenvolve interfaces e integra com APIs REST"),
        (5, "Arquiteto de Software", "Define padrões arquiteturais e decisões técnicas"),
        (6, "Analista de Requisitos", "Levanta, documenta e valida requisitos"),
        (7, "QA / Testador", "Planeja e executa testes manuais e automatizados"),
        (8, "DevOps Engineer", "Configura pipelines CI/CD e infraestrutura"),
        (9, "UX Designer", "Cria wireframes, protótipos e pesquisas de usabilidade"),
        (10, "Tech Lead", "Coordena decisões técnicas e revisa código"),
        (11, "Flow Manager", "Gerencia fluxo de trabalho e políticas Kanban"),
        (12, "Service Request Manager", "Prioriza demandas e classes de serviço"),
        (13, "XP Coach", "Orienta práticas de Extreme Programming na equipe"),
        (14, "Cliente On-site", "Representa stakeholders e valida entregas"),
        (15, "Gerente de Projeto", "Coordena escopo, cronograma e riscos do projeto"),
        (16, "Desenvolvedor Full Stack", "Atua em frontend e backend do produto"),
        (17, "Especialista de Domínio", "Fornece conhecimento de negócio à equipe"),
        (18, "Facilitador de Cerimônias", "Conduz reuniões e dinâmicas de melhoria"),
        (19, "Analista de Negócios", "Traduz necessidades de negócio em requisitos"),
        (20, "Líder Técnico", "Governa qualidade técnica e padrões de engenharia"),
    ]
    write_csv(lib / "roles.csv", "id;name;description", [f"{i};{n};{d}" for i, n, d in roles])

    artifacts = [
        (1, "Documento de Visão", "Problema, stakeholders e objetivos do produto", False),
        (2, "Backlog do Produto", "Lista priorizada de histórias e épicos", False),
        (3, "Especificação de Requisitos", "Requisitos funcionais e não funcionais detalhados", False),
        (4, "Diagrama de Arquitetura", "Componentes, integrações e fluxos do sistema", True),
        (5, "Protótipo de Interface", "Mockups ou wireframes das telas principais", True),
        (6, "Plano de Testes", "Casos de teste e critérios de aceitação", False),
        (7, "Código-fonte", "Implementação versionada no repositório Git", False),
        (8, "Relatório de Cobertura", "Métricas de cobertura de testes", True),
        (9, "Notas de Release", "Changelog com funcionalidades e correções", False),
        (10, "Manual de Deploy", "Instruções de build e publicação", True),
        (11, "Board Kanban", "Visualização do fluxo de trabalho em colunas", False),
        (12, "Políticas de Fluxo Explícitas", "Regras de pull, WIP e classes de serviço", False),
        (13, "Métricas de Lead e Cycle Time", "Indicadores de desempenho do fluxo", True),
        (14, "User Story", "História de usuário com critérios de aceitação", False),
        (15, "Incremento de Produto", "Versão utilizável entregue ao final da iteração", False),
        (16, "Arquitetura Baseline", "Arquitetura de referência validada", False),
        (17, "Modelo de Casos de Uso", "Atores e casos de uso principais", False),
        (18, "Build Iterativo", "Pacote de software pronto para validação", False),
        (19, "Protótipo de Risco", "Prova de conceito para mitigar risco técnico", True),
        (20, "Sprint Backlog", "Itens selecionados e plano da sprint atual", False),
    ]
    write_csv(
        lib / "artifacts.csv",
        "id;name;description;optional",
        [f"{i};{n};{d};{str(o).lower()}" for i, n, d, o in artifacts],
    )

    tools = [
        (1, "Jira", "Gestão ágil de backlog, sprints e issues"),
        (2, "GitHub", "Versionamento, pull requests e CI/CD"),
        (3, "Figma", "Design colaborativo e protótipos"),
        (4, "SonarQube", "Análise estática de qualidade de código"),
        (5, "Docker", "Containerização para dev e produção"),
        (6, "Postman", "Testes e documentação de APIs REST"),
        (7, "Confluence", "Documentação de requisitos e decisões"),
        (8, "Jenkins", "Automação de build, teste e deploy"),
        (9, "Draw.io", "Diagramas de arquitetura e fluxos"),
        (10, "Slack", "Comunicação da equipe e integrações"),
        (11, "Trello", "Boards visuais para fluxo Kanban"),
        (12, "Miro", "Mapas de fluxo de valor e workshops"),
    ]
    write_csv(lib / "tools.csv", "id;name;description", [f"{i};{n};{d}" for i, n, d in tools])

    guidelines = [
        (1, "Definition of Ready", "História só entra na sprint com critérios de prontidão"),
        (2, "Definition of Done", "Critérios mínimos para considerar entrega concluída"),
        (3, "Code Review obrigatório", "Pull request revisado por pelo menos um sênior"),
        (4, "Cobertura mínima de testes", "Novas funcionalidades mantêm cobertura acima de 80%"),
        (5, "Conventional Commits", "Mensagens de commit no padrão Conventional Commits"),
        (6, "Pair Programming", "Atividades críticas desenvolvidas em par"),
        (7, "Trunk-Based Development", "Integrações frequentes na branch principal"),
        (8, "Documentar ADRs", "Decisões arquiteturais registradas formalmente"),
        (9, "Segurança por padrão", "Validar autenticação e autorização em novas APIs"),
        (10, "Retrospectiva contínua", "Registrar lições aprendidas ao final de cada ciclo"),
        (11, "Limites de WIP", "Respeitar limites de trabalho em progresso por coluna"),
        (12, "Desenvolvimento Orientado a Testes", "Escrever testes antes ou junto ao código"),
    ]
    write_csv(lib / "guidelines.csv", "id;name;description", [f"{i};{n};{d}" for i, n, d in guidelines])

    templates = [
        (1, "Template de História de Usuário", "Como [persona], quero [ação], para [benefício]"),
        (2, "Template de Caso de Teste", "Pré-condições, passos e resultado esperado"),
        (3, "Template de ADR", "Contexto, opções e consequências da decisão"),
        (4, "Template de Sprint Planning", "Agenda com metas e capacidade da equipe"),
        (5, "Template de Retrospectiva", "Formato Start/Stop/Continue"),
        (6, "Template de Pull Request", "Checklist de revisão e breaking changes"),
        (7, "Template de Especificação de API", "Contrato OpenAPI com endpoints e schemas"),
        (8, "Template de Bug Report", "Passos de reprodução e severidade"),
        (9, "Template de Release Notes", "Novidades, correções e breaking changes"),
        (10, "Template de Diagrama C4", "Contexto, containers, componentes e código"),
        (11, "Template de Caso de Uso", "Ator, fluxo principal e alternativos"),
        (12, "Template de Política de Fluxo", "Regras explícitas de entrada e saída de colunas"),
    ]
    write_csv(lib / "templates.csv", "id;name;description", [f"{i};{n};{d}" for i, n, d in templates])

    art_tmpl = [
        (1, 10), (2, 1), (3, 1), (4, 10), (6, 2), (7, 6), (9, 9), (11, 12),
        (12, 12), (14, 1), (16, 10), (17, 11), (20, 4),
    ]
    write_csv(
        lib / "rel_artifacts__templates.csv",
        "artifacts_id;templates_id",
        [f"{a};{t}" for a, t in art_tmpl],
    )


def generate_processes() -> None:
    write_csv(
        BASE / "process.csv",
        "id;process_name;process_description",
        [
            "1;Scrum (Catalog);Framework ágil iterativo com sprints, papéis definidos e entregas incrementais",
            "2;Kanban (Catalog);Fluxo contínuo de trabalho com limitação de WIP e visualização do pipeline",
            "3;Extreme Programming (XP) (Catalog);Práticas de engenharia como TDD, pair programming e integração contínua",
            "4;RUP Simplificado (Catalog);Processo iterativo com fases de iniciação, elaboração, construção e transição",
        ],
    )

    write_process_data(
        "scrum",
        [
            (101, "Product Backlog", "Gestão contínua do Product Goal e itens priorizados", 1),
            (102, "Planejamento da Sprint", "Evento de planejamento: meta, seleção e plano de entrega", 1),
            (103, "Execução da Sprint", "Daily Scrum e trabalho de desenvolvimento do Incremento", 1),
            (104, "Encerramento da Sprint", "Sprint Review e Sprint Retrospective", 1),
            (105, "Release", "Estabilização e implantação do Incremento em produção", 1),
        ],
        [
            {
                "id": 1001,
                "phase": 101,
                "name": "Estabelecer Product Goal e visão",
                "desc": "Definir Product Goal e alinhar visão de produto com stakeholders",
                "input": "Necessidade de negócio e contexto de mercado identificados",
                "responsible": [1],
                "participants": [2, 19],
                "produced": [1],
                "tools": [7],
                "templates": [10],
                "guidelines": [8],
            },
            {
                "id": 1002,
                "phase": 101,
                "name": "Ordenar Product Backlog por valor",
                "desc": "Priorizar itens do Product Backlog por valor, risco e dependências",
                "input": "Product Goal e Documento de Visão aprovados",
                "responsible": [1],
                "participants": [2, 10],
                "required": [1],
                "produced": [2],
                "tools": [1],
                "guidelines": [1],
                "deps": [1001],
            },
            {
                "id": 1003,
                "phase": 101,
                "name": "Refinar Product Backlog",
                "desc": "Refinar itens até atender Definition of Ready para próxima sprint",
                "input": "Product Backlog priorizado disponível",
                "responsible": [1],
                "participants": [3, 4, 7],
                "required": [2],
                "produced": [3, 14],
                "tools": [1, 7],
                "templates": [1],
                "guidelines": [1, 2],
                "deps": [1002],
            },
            {
                "id": 1004,
                "phase": 102,
                "name": "Conduzir Sprint Planning",
                "desc": "Definir Sprint Goal, selecionar PBIs e planejar entrega do Incremento",
                "input": "Product Backlog refinado e capacidade da equipe conhecidos",
                "responsible": [2],
                "participants": [1, 3, 4],
                "required": [2, 3, 14],
                "produced": [20, 6],
                "tools": [1],
                "templates": [4],
                "guidelines": [1, 2],
                "deps": [1003],
            },
            {
                "id": 1005,
                "phase": 103,
                "name": "Conduzir Daily Scrum",
                "desc": "Inspecionar progresso em direção ao Sprint Goal e adaptar o plano diário",
                "input": "Sprint em andamento com Sprint Backlog ativo",
                "responsible": [2],
                "participants": [1, 3, 4],
                "required": [20],
                "tools": [1, 10],
                "guidelines": [10],
                "deps": [1004],
            },
            {
                "id": 1006,
                "phase": 103,
                "name": "Desenvolver Incremento da Sprint",
                "desc": "Transformar PBIs selecionados em entrega utilizável dentro da sprint",
                "input": "Sprint Backlog comprometido pela equipe",
                "responsible": [3],
                "participants": [4, 10],
                "required": [20, 14],
                "produced": [7],
                "tools": [2],
                "guidelines": [2, 5, 7],
                "deps": [1004],
            },
            {
                "id": 1007,
                "phase": 103,
                "name": "Integrar e verificar Incremento",
                "desc": "Integrar trabalho da equipe e verificar que o Incremento atende ao DoD",
                "input": "Código desenvolvido e integrado na branch principal",
                "responsible": [3],
                "participants": [4, 7],
                "required": [7],
                "produced": [8, 15],
                "tools": [2, 8],
                "templates": [2],
                "guidelines": [2, 4, 7],
                "deps": [1006],
            },
            {
                "id": 1008,
                "phase": 103,
                "name": "Inspecionar qualidade técnica do Incremento",
                "desc": "Revisar código e validar critérios técnicos da Definition of Done",
                "input": "Incremento integrado com testes automatizados verdes",
                "responsible": [10],
                "participants": [3, 4],
                "required": [7, 8],
                "produced": [7],
                "tools": [2, 4],
                "templates": [6],
                "guidelines": [3, 9],
                "deps": [1007],
            },
            {
                "id": 1009,
                "phase": 104,
                "name": "Conduzir Sprint Review",
                "desc": "Inspecionar Incremento com stakeholders e adaptar Product Backlog",
                "input": "Incremento Done e pronto para demonstração",
                "responsible": [1],
                "participants": [2, 3, 4],
                "required": [15, 7],
                "produced": [2, 9],
                "tools": [1, 10],
                "templates": [9],
                "guidelines": [2],
                "deps": [1008],
            },
            {
                "id": 1010,
                "phase": 104,
                "name": "Conduzir Sprint Retrospective",
                "desc": "Inspecionar como foi a sprint e definir melhorias para a próxima",
                "input": "Sprint Review concluída e feedback registrado",
                "responsible": [2],
                "participants": [1, 3, 4],
                "required": [9],
                "tools": [10],
                "templates": [5],
                "guidelines": [10],
                "deps": [1009],
            },
            {
                "id": 1011,
                "phase": 105,
                "name": "Estabilizar candidato a release",
                "desc": "Hardening do Incremento e preparação do pacote para produção",
                "input": "Incremento aprovado na Sprint Review",
                "responsible": [8],
                "participants": [10, 7],
                "required": [15, 8],
                "produced": [18, 9],
                "tools": [8, 5],
                "templates": [9],
                "guidelines": [2, 4],
                "deps": [1009],
            },
            {
                "id": 1012,
                "phase": 105,
                "name": "Implantar Incremento em produção",
                "desc": "Publicar Incremento no ambiente produtivo com validação pós-deploy",
                "input": "Candidato a release estabilizado e notas publicadas",
                "responsible": [8],
                "participants": [10],
                "required": [9, 18],
                "produced": [10],
                "tools": [8, 5],
                "guidelines": [9],
                "deps": [1011],
            },
        ],
    )

    write_process_data(
        "kanban",
        [
            (201, "Design do Sistema de Fluxo (STATIK)", "Análise de demanda e mapeamento do workflow", 2),
            (202, "Políticas Explícitas e WIP", "Limites de WIP e regras de pull do sistema", 2),
            (203, "Fluxo de Entrega", "Replenishment, pull e execução contínua de itens", 2),
            (204, "Cadências de Melhoria", "Service Delivery Review e Risk Review", 2),
        ],
        [
            {
                "id": 2001,
                "phase": 201,
                "name": "Conduzir análise de demanda",
                "desc": "Analisar tipos de demanda, padrões e fontes de variabilidade",
                "input": "Contexto de serviço e tipos de trabalho identificados",
                "responsible": [11],
                "participants": [12, 17],
                "produced": [11],
                "tools": [12],
                "templates": [12],
                "guidelines": [11],
            },
            {
                "id": 2002,
                "phase": 201,
                "name": "Mapear fluxo de trabalho atual",
                "desc": "Mapear knowledge discovery workflow desde a ideia até a entrega",
                "input": "Análise de demanda concluída",
                "responsible": [11],
                "participants": [16, 17],
                "required": [11],
                "produced": [11],
                "tools": [12, 9],
                "deps": [2001],
            },
            {
                "id": 2003,
                "phase": 201,
                "name": "Definir classes de serviço",
                "desc": "Classificar demandas em Expedite, Fixed Date, Standard e Intangible",
                "input": "Fluxo de trabalho mapeado e validado",
                "responsible": [12],
                "participants": [11, 19],
                "required": [11],
                "produced": [12],
                "tools": [7],
                "templates": [12],
                "deps": [2002],
            },
            {
                "id": 2004,
                "phase": 202,
                "name": "Estabelecer limites de WIP",
                "desc": "Definir limites de trabalho em progresso por coluna e swimlane",
                "input": "Classes de serviço e capacidade do sistema conhecidas",
                "responsible": [11],
                "participants": [16],
                "required": [12],
                "produced": [12],
                "tools": [11],
                "guidelines": [11],
                "deps": [2003],
            },
            {
                "id": 2005,
                "phase": 202,
                "name": "Formalizar políticas explícitas de fluxo",
                "desc": "Documentar políticas de pull, DoR e DoD por etapa do fluxo",
                "input": "Limites de WIP acordados pela equipe",
                "responsible": [11],
                "participants": [12, 7],
                "required": [12],
                "produced": [12],
                "tools": [7, 11],
                "templates": [12],
                "guidelines": [1, 2, 11],
                "deps": [2004],
            },
            {
                "id": 2006,
                "phase": 203,
                "name": "Conduzir reunião de replenishment",
                "desc": "Reabastecer o ponto de compromisso com itens prontos para pull",
                "input": "Políticas de fluxo publicadas e capacidade disponível",
                "responsible": [12],
                "participants": [11, 19],
                "required": [2, 12],
                "produced": [14],
                "tools": [11, 1],
                "guidelines": [1, 11],
                "deps": [2005],
            },
            {
                "id": 2007,
                "phase": 203,
                "name": "Puxar item conforme capacidade disponível",
                "desc": "Puxar próximo item respeitando WIP e políticas de classe de serviço",
                "input": "Slot de WIP disponível no ponto de compromisso",
                "responsible": [16],
                "participants": [11],
                "required": [14, 12],
                "tools": [11],
                "guidelines": [11],
                "deps": [2006],
            },
            {
                "id": 2008,
                "phase": 203,
                "name": "Executar e validar item de trabalho",
                "desc": "Desenvolver, revisar e validar item até critérios de saída da coluna",
                "input": "Item puxado para coluna de execução",
                "responsible": [16],
                "participants": [7, 10],
                "required": [14],
                "produced": [7, 15],
                "tools": [2, 4],
                "guidelines": [2, 3],
                "deps": [2007],
            },
            {
                "id": 2009,
                "phase": 203,
                "name": "Registrar métricas de fluxo",
                "desc": "Coletar lead time, throughput e aging de itens em progresso",
                "input": "Itens entregues no período de medição",
                "responsible": [11],
                "participants": [12],
                "required": [15],
                "produced": [13],
                "tools": [1],
                "guidelines": [10],
                "deps": [2008],
            },
            {
                "id": 2010,
                "phase": 204,
                "name": "Conduzir Service Delivery Review",
                "desc": "Avaliar desempenho do serviço entregue ao cliente e ao negócio",
                "input": "Métricas de fluxo consolidadas do período",
                "responsible": [12],
                "participants": [11, 19, 18],
                "required": [13],
                "tools": [1, 10],
                "guidelines": [10],
                "deps": [2009],
            },
            {
                "id": 2011,
                "phase": 204,
                "name": "Conduzir Risk Review e evoluir o sistema",
                "desc": "Revisar riscos do fluxo e ajustar design e políticas do sistema Kanban",
                "input": "Service Delivery Review concluída com ações identificadas",
                "responsible": [11],
                "participants": [12, 18],
                "required": [13, 12],
                "produced": [12],
                "tools": [12, 10],
                "templates": [5],
                "guidelines": [10, 11],
                "deps": [2010],
            },
        ],
    )

    write_process_data(
        "xp",
        [
            (301, "Release Planning", "Planning game e seleção de escopo do release", 3),
            (302, "Ciclo da Story", "Aceitação, TDD, pair programming e integração contínua", 3),
            (303, "Práticas de Design Contínuo", "Design simples, metáfora e padrões coletivos", 3),
            (304, "Feedback e Release", "Aceitação, small release e feedback do cliente on-site", 3),
        ],
        [
            {
                "id": 3001,
                "phase": 301,
                "name": "Conduzir Planning Game de release",
                "desc": "Cliente e equipe definem escopo e prioridades do próximo release",
                "input": "Product Backlog com visão de release acordada",
                "responsible": [13],
                "participants": [14, 16],
                "required": [2],
                "produced": [2],
                "tools": [1, 7],
                "templates": [4],
                "guidelines": [1],
            },
            {
                "id": 3002,
                "phase": 301,
                "name": "Estimar stories com planning poker",
                "desc": "Estimar esforço das stories candidatas com consenso da equipe",
                "input": "Stories selecionadas no planning game de release",
                "responsible": [14],
                "participants": [16, 13],
                "required": [14],
                "produced": [14],
                "tools": [1],
                "templates": [1],
                "deps": [3001],
            },
            {
                "id": 3003,
                "phase": 301,
                "name": "Selecionar stories da iteração",
                "desc": "Escolher stories que a equipe compromete entregar na iteração",
                "input": "Stories estimadas e capacidade da iteração definida",
                "responsible": [13],
                "participants": [14, 16],
                "required": [14, 2],
                "produced": [20, 6],
                "tools": [1],
                "templates": [4],
                "guidelines": [1, 2],
                "deps": [3002],
            },
            {
                "id": 3004,
                "phase": 302,
                "name": "Escrever testes de aceitação da story",
                "desc": "Especificar critérios de aceitação executáveis antes da implementação",
                "input": "Story selecionada para a iteração com escopo claro",
                "responsible": [14],
                "participants": [7, 16],
                "required": [14, 20],
                "produced": [6],
                "tools": [6, 7],
                "templates": [2],
                "guidelines": [2, 12],
                "deps": [3003],
            },
            {
                "id": 3005,
                "phase": 302,
                "name": "Aplicar ciclo TDD na story",
                "desc": "Desenvolver com ciclo Red-Green-Refactor guiado por testes unitários",
                "input": "Testes de aceitação e unitários iniciais definidos",
                "responsible": [16],
                "participants": [7],
                "required": [6, 14],
                "produced": [7],
                "tools": [2],
                "guidelines": [12, 2],
                "deps": [3004],
            },
            {
                "id": 3006,
                "phase": 302,
                "name": "Desenvolver story em pair programming",
                "desc": "Implementar story em par para reduzir defeitos e disseminar conhecimento",
                "input": "Story em desenvolvimento com testes guia",
                "responsible": [16],
                "participants": [3, 4],
                "required": [7],
                "produced": [7],
                "tools": [2],
                "guidelines": [6],
                "deps": [3005],
            },
            {
                "id": 3007,
                "phase": 302,
                "name": "Integrar continuamente na mainline",
                "desc": "Integrar alterações na linha principal várias vezes ao dia",
                "input": "Story implementada com testes automatizados verdes",
                "responsible": [8],
                "participants": [16, 20],
                "required": [7],
                "produced": [18],
                "tools": [8, 2],
                "guidelines": [7, 5],
                "deps": [3006],
            },
            {
                "id": 3008,
                "phase": 303,
                "name": "Aplicar design simples",
                "desc": "Manter o design mais simples que atenda aos requisitos atuais (YAGNI)",
                "input": "Story em implementação com requisitos claros",
                "responsible": [20],
                "participants": [16],
                "required": [14],
                "guidelines": [8],
                "deps": [3004],
            },
            {
                "id": 3009,
                "phase": 303,
                "name": "Evoluir metáfora do sistema",
                "desc": "Manter vocabulário compartilhado que orienta decisões de design",
                "input": "Visão de domínio e stories da iteração alinhadas",
                "responsible": [13],
                "participants": [14, 16],
                "produced": [4],
                "tools": [9, 7],
                "templates": [10],
                "deps": [3003],
            },
            {
                "id": 3010,
                "phase": 303,
                "name": "Aplicar padrões de codificação coletivos",
                "desc": "Garantir código legível e ownership coletivo via padrões compartilhados",
                "input": "Código integrado na mainline da iteração",
                "responsible": [20],
                "participants": [16, 3, 4],
                "required": [7],
                "tools": [4, 2],
                "guidelines": [3, 5],
                "deps": [3006],
            },
            {
                "id": 3011,
                "phase": 304,
                "name": "Validar stories com testes de aceitação",
                "desc": "Cliente valida stories executando critérios de aceitação acordados",
                "input": "Build iterativo com stories integradas disponível",
                "responsible": [14],
                "participants": [7, 13],
                "required": [18, 6],
                "produced": [8, 15],
                "tools": [6],
                "templates": [2],
                "guidelines": [2, 4],
                "deps": [3007],
            },
            {
                "id": 3012,
                "phase": 304,
                "name": "Publicar small release",
                "desc": "Entregar release pequena, frequente e utilizável em produção ou homologação",
                "input": "Stories aceitas pelo cliente on-site",
                "responsible": [8],
                "participants": [16],
                "required": [15, 8],
                "produced": [9, 18],
                "tools": [8],
                "templates": [9],
                "guidelines": [2],
                "deps": [3011],
            },
            {
                "id": 3013,
                "phase": 304,
                "name": "Incorporar feedback do cliente on-site",
                "desc": "Adaptar Product Backlog com feedback direto do cliente on-site",
                "input": "Small release demonstrada ao cliente",
                "responsible": [14],
                "participants": [13, 19],
                "required": [9, 15],
                "produced": [2],
                "tools": [10, 1],
                "guidelines": [10],
                "deps": [3012],
            },
        ],
    )

    write_process_data(
        "rup",
        [
            (401, "Iniciação", "Marco Lifecycle Objectives: visão, escopo e viabilidade", 4),
            (402, "Elaboração", "Marco Lifecycle Architecture: requisitos e arquitetura baseline", 4),
            (403, "Construção", "Marco Operational Capability: implementação e integração iterativa", 4),
            (404, "Transição", "Marco Product Release: aceitação, deploy e encerramento", 4),
        ],
        [
            {
                "id": 4001,
                "phase": 401,
                "name": "Capturar visão e escopo do negócio",
                "desc": "Disciplina Business Modeling: documentar visão, escopo e restrições",
                "input": "Oportunidade de negócio e contexto organizacional identificados",
                "responsible": [15],
                "participants": [19, 5],
                "produced": [1],
                "tools": [7],
                "templates": [10],
            },
            {
                "id": 4002,
                "phase": 401,
                "name": "Identificar atores e casos de uso essenciais",
                "desc": "Disciplina Requirements: mapear 20% dos casos que entregam 80% do valor",
                "input": "Documento de Visão e escopo aprovados",
                "responsible": [6],
                "participants": [19, 17],
                "required": [1],
                "produced": [17],
                "tools": [9],
                "templates": [11],
                "deps": [4001],
            },
            {
                "id": 4003,
                "phase": 401,
                "name": "Avaliar viabilidade e riscos do projeto",
                "desc": "Disciplina Project Management: analisar viabilidade e plano preliminar",
                "input": "Casos de uso essenciais e restrições conhecidas",
                "responsible": [15],
                "participants": [5, 10],
                "required": [17],
                "produced": [4],
                "tools": [9, 7],
                "guidelines": [8],
                "deps": [4002],
            },
            {
                "id": 4004,
                "phase": 402,
                "name": "Detalhar requisitos e regras de negócio",
                "desc": "Disciplina Requirements: especificar requisitos funcionais e não funcionais",
                "input": "Lifecycle Objectives aprovado e riscos iniciais mapeados",
                "responsible": [6],
                "participants": [19, 9, 17],
                "required": [17, 4],
                "produced": [3],
                "tools": [7],
                "templates": [1],
                "guidelines": [1],
                "deps": [4003],
            },
            {
                "id": 4005,
                "phase": 402,
                "name": "Definir arquitetura baseline",
                "desc": "Disciplina Analysis and Design: estabelecer arquitetura estável para construção",
                "input": "Especificação de requisitos validada na elaboração",
                "responsible": [5],
                "participants": [10, 8],
                "required": [3],
                "produced": [16],
                "tools": [9],
                "templates": [10, 3],
                "guidelines": [8],
                "deps": [4004],
            },
            {
                "id": 4006,
                "phase": 402,
                "name": "Construir protótipo de risco arquitetural",
                "desc": "Disciplina Analysis and Design: provar conceito para mitigar risco técnico crítico",
                "input": "Riscos arquiteturais priorizados na elaboração",
                "responsible": [5],
                "participants": [16, 7],
                "required": [3, 4],
                "produced": [19],
                "tools": [3, 6],
                "templates": [7],
                "deps": [4004],
            },
            {
                "id": 4007,
                "phase": 403,
                "name": "Implementar componentes da iteração",
                "desc": "Disciplina Implementation: codificar componentes conforme arquitetura baseline",
                "input": "Lifecycle Architecture aprovada e baseline disponível",
                "responsible": [10],
                "participants": [3, 4, 16],
                "required": [16, 3],
                "produced": [7],
                "tools": [2],
                "guidelines": [3, 5],
                "deps": [4005],
            },
            {
                "id": 4008,
                "phase": 403,
                "name": "Executar testes de integração de componentes",
                "desc": "Disciplina Test: validar integração entre componentes da iteração",
                "input": "Componentes da iteração implementados",
                "responsible": [7],
                "participants": [3, 4, 10],
                "required": [7],
                "produced": [8, 6],
                "tools": [4, 6],
                "templates": [2],
                "guidelines": [4],
                "deps": [4007],
            },
            {
                "id": 4009,
                "phase": 403,
                "name": "Produzir build de iteração",
                "desc": "Disciplina Configuration and Change Management: empacotar build validado",
                "input": "Testes de integração da iteração aprovados",
                "responsible": [8],
                "participants": [10],
                "required": [8, 7],
                "produced": [18],
                "tools": [8, 5],
                "guidelines": [2, 7],
                "deps": [4008],
            },
            {
                "id": 4010,
                "phase": 404,
                "name": "Conduzir testes de aceitação com usuários",
                "desc": "Disciplina Test: validar solução com usuários em ambiente beta ou UAT",
                "input": "Build de iteração disponível para validação",
                "responsible": [6],
                "participants": [19, 9, 7],
                "required": [18, 6],
                "produced": [15],
                "tools": [6],
                "templates": [2],
                "guidelines": [2],
                "deps": [4009],
            },
            {
                "id": 4011,
                "phase": 404,
                "name": "Implantar solução no ambiente alvo",
                "desc": "Disciplina Deployment: publicar solução no ambiente de produção",
                "input": "Aceite dos usuários e critérios de release atendidos",
                "responsible": [8],
                "participants": [10],
                "required": [18, 15],
                "produced": [10],
                "tools": [8, 5],
                "guidelines": [9],
                "deps": [4010],
            },
            {
                "id": 4012,
                "phase": 404,
                "name": "Encerrar fase e transferir operação",
                "desc": "Disciplinas Project Management e Environment: handover e lições aprendidas",
                "input": "Solução implantada e estável no ambiente alvo",
                "responsible": [15],
                "participants": [6, 8],
                "required": [10, 9],
                "produced": [1],
                "tools": [7],
                "guidelines": [10],
                "deps": [4011],
            },
        ],
    )


if __name__ == "__main__":
    generate_library()
    generate_processes()
    print("Catalog CSVs generated at", BASE)
